# Generated by Django 4.0.6 on 2025-01-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='numero_bus',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
