# Generated by Django 4.0.6 on 2025-01-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0002_bus_numero_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='numero_bus',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
