# Generated by Django 4.0.6 on 2025-01-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0003_alter_bus_numero_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='nombre_bus',
            field=models.CharField(default='Cotopaxi', max_length=15),
        ),
    ]
