# Generated by Django 4.0.6 on 2025-01-13 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0005_alter_horario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Transportes.bus'),
        ),
    ]
