# Generated by Django 4.0.6 on 2025-01-13 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0006_horario_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
