# Generated by Django 4.0.6 on 2025-01-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0007_horario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='fecha',
        ),
    ]
