# Generated by Django 4.0.6 on 2025-01-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0008_remove_horario_dia_remove_horario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
