# Generated by Django 4.0.6 on 2025-01-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0010_alter_horario_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='precio',
        ),
    ]
