# Generated by Django 4.0.6 on 2025-01-13 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0011_remove_horario_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='ruta',
        ),
        migrations.AddField(
            model_name='venta',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transportes.horario'),
        ),
    ]
