# Generated by Django 4.0.6 on 2025-01-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0015_alter_venta_bus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
