# Generated by Django 4.0.6 on 2025-01-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0017_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
