# Generated by Django 4.0.6 on 2025-01-13 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0018_alter_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='disponible',
        ),
    ]
