# Generated by Django 4.0.6 on 2025-01-13 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0019_remove_asiento_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transportes.bus'),
        ),
    ]
