# Generated by Django 4.0.6 on 2025-01-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0021_alter_asiento_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ruta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Transportes.ruta'),
        ),
    ]
