# Generated by Django 4.0.6 on 2025-01-13 04:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0023_alter_venta_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
