# Generated by Django 4.0.6 on 2025-01-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0024_venta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
