# Generated by Django 4.0.6 on 2025-01-13 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0025_alter_venta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transportes.horario'),
        ),
    ]
