# Generated by Django 4.0.6 on 2025-01-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0026_alter_venta_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asiento',
            name='bus',
        ),
    ]
