# Generated by Django 4.0.6 on 2025-01-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0027_remove_asiento_bus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asiento',
        ),
    ]
