# Generated by Django 4.0.6 on 2025-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0028_delete_asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='asiento',
            field=models.CharField(max_length=20),
        ),
    ]
