# Generated by Django 4.0.6 on 2025-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0029_alter_venta_asiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='asiento',
            field=models.CharField(max_length=200),
        ),
    ]
