# Generated by Django 4.0.6 on 2025-01-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0030_alter_venta_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad_asientos',
            field=models.IntegerField(default=0),
        ),
    ]
