# Generated by Django 4.0.6 on 2025-01-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0031_venta_cantidad_asientos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad_asientos',
            field=models.IntegerField(),
        ),
    ]
