# Generated by Django 4.0.6 on 2025-01-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0032_alter_venta_cantidad_asientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad_asientos',
        ),
    ]
