# Generated by Django 4.0.6 on 2025-01-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transportes', '0036_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='asientos',
            field=models.ManyToManyField(to='Transportes.asiento'),
        ),
    ]
